# Generated by Django 6.0.3 on 2026-03-11 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_consultation'),
    ]

    operations = [
        migrations.AddField(
            model_name='lawyer',
            name='location',
            field=models.CharField(default='unkown', max_length=150),
            preserve_default=False,
        ),
    ]
